window.subjectData = {
  accounting: {
    id: 'accounting',
    name: "재무회계",
    color: "#3b82f6",
    icon: "📊",
    chapters: [
      { id: 1, title: "제01장 개념체계와 재무제표 표시", difficulty: 2 },
      { id: 2, title: "제02장 수 익", difficulty: 4 },
      { id: 3, title: "제03장 건설계약", difficulty: 3 },
      { id: 4, title: "제04장 현금흐름표", difficulty: 4 },
      { id: 5, title: "제05장 재고자산과 농림어업", difficulty: 3 },
      { id: 6, title: "제06장 유형자산", difficulty: 3 },
      { id: 7, title: "제07장 차입원가", difficulty: 3 },
      { id: 8, title: "제08장 무형자산", difficulty: 2 },
      { id: 9, title: "제09장 금융부채", difficulty: 3 },
      { id: 10, title: "제10장 충당부채와 보고기간후사건", difficulty: 2 },
      { id: 11, title: "제11장 자 본", difficulty: 4 },
      { id: 12, title: "제12장 금융자산(Ⅰ): 지분상품과 채무상품", difficulty: 4 },
      { id: 13, title: "제13장 금융자산(Ⅱ): 현금과 수취채권", difficulty: 3 },
      { id: 14, title: "제14장 복합금융상품", difficulty: 5 },
      { id: 15, title: "제15장 종업원급여", difficulty: 4 },
      { id: 16, title: "제16장 주식기준보상", difficulty: 4 },
      { id: 17, title: "제17장 리스회계", difficulty: 4 },
      { id: 18, title: "제18장 투자부동산과 매각예정비유동자산", difficulty: 2 },
      { id: 19, title: "제19장 법인세회계", difficulty: 5 },
      { id: 20, title: "제20장 회계변경과 오류수정", difficulty: 3 },
      { id: 21, title: "제21장 주당이익", difficulty: 4 },
      { id: 22, title: "제22장 사업결합", difficulty: 5 },
      { id: 23, title: "제23장 관계기업과 공동기업 투자", difficulty: 4 },
      { id: 24, title: "제24장 연결회계", difficulty: 5 },
      { id: 25, title: "제25장 환율변동효과", difficulty: 4 },
      { id: 26, title: "제26장 파생상품", difficulty: 4 }
    ]
  },
  tax: {
    id: 'tax',
    name: "세법",
    color: "#ef4444",
    icon: "⚖️",
    chapters: [
      { id: 101, title: "[법인세] 제01장 총설", difficulty: 2 },
      { id: 102, title: "[법인세] 제02장 세무조정과 소득처분", difficulty: 3 },
      { id: 103, title: "[법인세] 제03장 익금(1): 범위", difficulty: 4 },
      { id: 104, title: "[법인세] 제04장 익금(2): 의제배당", difficulty: 5 },
      { id: 105, title: "[법인세] 제05장 손금(1): 범위", difficulty: 3 },
      { id: 106, title: "[법인세] 제06장 손금(2): 접대비, 기부금", difficulty: 3 },
      { id: 107, title: "[법인세] 제07장 손금(3): 감가상각비", difficulty: 5 },
      { id: 108, title: "[법인세] 제08장 손금(4): 지급이자", difficulty: 4 },
      { id: 109, title: "[법인세] 제09장 손익 귀속시기", difficulty: 4 },
      { id: 110, title: "[법인세] 제10장 자산의 취득과 평가", difficulty: 4 },
      { id: 111, title: "[법인세] 제11장 충당금(1): 퇴직급여", difficulty: 4 },
      { id: 112, title: "[법인세] 제12장 충당금(2): 대손", difficulty: 4 },
      { id: 113, title: "[법인세] 제13장 충당금(3): 일시상각", difficulty: 3 },
      { id: 114, title: "[법인세] 제14장 부당행위계산부인", difficulty: 5 },
      { id: 115, title: "[법인세] 제15장 과세표준과 세액", difficulty: 4 },
      { id: 116, title: "[법인세] 제16장 신고와 납부", difficulty: 2 },
      { id: 117, title: "[법인세] 제17장 기업구조개편", difficulty: 5 },
      { id: 118, title: "[법인세] 제18장 연결납세", difficulty: 4 },
      { id: 119, title: "[법인세] 제19장 그 밖의 법인세", difficulty: 2 },
      
      { id: 201, title: "[소득세] 제1장 총설", difficulty: 2 },
      { id: 202, title: "[소득세] 제2장 금융소득", difficulty: 4 },
      { id: 203, title: "[소득세] 제3장 사업소득", difficulty: 4 },
      { id: 204, title: "[소득세] 제4장 근로/연금/기타소득", difficulty: 3 },
      { id: 205, title: "[소득세] 제5장 소득계산특례", difficulty: 4 },
      { id: 206, title: "[소득세] 제6장 과세표준", difficulty: 3 },
      { id: 207, title: "[소득세] 제7장 산출/차감납부세액", difficulty: 4 },
      { id: 208, title: "[소득세] 제8장 퇴직소득", difficulty: 3 },
      { id: 209, title: "[소득세] 제9장 양도소득", difficulty: 5 },
      { id: 210, title: "[소득세] 제10장 신고납부", difficulty: 2 },
      { id: 211, title: "[소득세] 제11장 동업기업", difficulty: 3 },
      { id: 212, title: "[소득세] 제12장 비거주자/외국법인", difficulty: 2 },

      { id: 301, title: "[부가세] 제1장 총설", difficulty: 1 },
      { id: 302, title: "[부가세] 제2장 과세거래", difficulty: 4 },
      { id: 303, title: "[부가세] 제3장 영세율/면세", difficulty: 3 },
      { id: 304, title: "[부가세] 제4장 세금계산서/영수증", difficulty: 2 },
      { id: 305, title: "[부가세] 제5장 과세표준/매출세액", difficulty: 5 },
      { id: 306, title: "[부가세] 제6장 매입세액/차가감", difficulty: 5 },
      { id: 307, title: "[부가세] 제7장 겸영사업자", difficulty: 5 },
      { id: 308, title: "[부가세] 제8장 신고납부", difficulty: 2 },
      { id: 309, title: "[부가세] 제9장 간이과세", difficulty: 4 },

      { id: 401, title: "[상증세] 제1장 상속세", difficulty: 4 },
      { id: 402, title: "[상증세] 제2장 증여세", difficulty: 4 },
      { id: 403, title: "[상증세] 제3장 재산의 평가", difficulty: 5 },
      { id: 404, title: "[상증세] 제4장 신고납부절차", difficulty: 2 },

      { id: 501, title: "[국기법] 제1장 총칙", difficulty: 2 },
      { id: 502, title: "[국기법] 제2장 국세부과원칙", difficulty: 2 },
      { id: 503, title: "[국기법] 제3장 납세의무", difficulty: 4 },
      { id: 504, title: "[국기법] 제4장 납세의무확장", difficulty: 4 },
      { id: 505, title: "[국기법] 제5장 국세/일반채권", difficulty: 4 },
      { id: 506, title: "[국기법] 제6장 과세", difficulty: 2 },
      { id: 507, title: "[국기법] 제7장 국세환급금", difficulty: 2 },
      { id: 508, title: "[국기법] 제8장 불복제도", difficulty: 3 },
      { id: 509, title: "[국기법] 제9장 납세자권리/보칙", difficulty: 2 }
    ]
  },
  finance: {
    id: 'finance',
    name: "재정학 연습",
    color: "#10b981",
    icon: "📈",
    chapters: [
      { id: 601, title: "제01장 재정학의 기초", difficulty: 2 },
      { id: 602, title: "제02장 경제적 효율성과 시장실패", difficulty: 3 },
      { id: 603, title: "제03장 외부성", difficulty: 4 },
      { id: 604, title: "제04장 공공재이론", difficulty: 4 },
      { id: 605, title: "제05장 공공선택이론", difficulty: 3 },
      { id: 606, title: "제06장 정부지출과 예산제도", difficulty: 3 },
      { id: 607, title: "제07장 비용-편익분석", difficulty: 3 },
      { id: 608, title: "제08장 조세의 기초이론", difficulty: 3 },
      { id: 609, title: "제09장 조세의 전가와 귀착", difficulty: 4 },
      { id: 610, title: "제10장 조세와 효율성: 초과부담", difficulty: 4 },
      { id: 611, title: "제11장 최적과세론", difficulty: 5 },
      { id: 612, title: "제12장 개별조세이론", difficulty: 3 },
      { id: 613, title: "제13장 조세의 경제적 효과", difficulty: 4 },
      { id: 614, title: "제14장 소득분배 및 사회보장", difficulty: 2 },
      { id: 615, title: "제15장 공공요금의 이론", difficulty: 3 },
      { id: 616, title: "제16장 공채론", difficulty: 2 },
      { id: 617, title: "제17장 지방재정", difficulty: 2 }
    ]
  },
  cost_accounting: {
    id: 'cost_accounting',
    name: "원가관리회계",
    color: "#f59e0b",
    icon: "⚙️",
    chapters: [
      { id: 701, title: "제01장 원가관리회계 개념", difficulty: 1 },
      { id: 702, title: "제02장 원가의 개념과 분류", difficulty: 2 },
      { id: 703, title: "제03장 제조기업의 원가흐름", difficulty: 3 },
      { id: 704, title: "제04장 원가배부/보조부문원가", difficulty: 4 },
      { id: 705, title: "제05장 개별원가계산", difficulty: 3 },
      { id: 706, title: "제06장 종합원가계산", difficulty: 5 },
      { id: 707, title: "제07장 공손품회계", difficulty: 4 },
      { id: 708, title: "제08장 연산품과 부산물", difficulty: 4 },
      { id: 709, title: "제09장 변동/초변동원가계산", difficulty: 3 },
      { id: 710, title: "제10장 활동기준원가계산(ABC)", difficulty: 3 },
      { id: 711, title: "제11장 원가추정", difficulty: 2 },
      { id: 712, title: "제12장 CVP 분석", difficulty: 4 },
      { id: 713, title: "제13장 관련원가분석", difficulty: 4 },
      { id: 714, title: "제14장 자본예산", difficulty: 4 },
      { id: 715, title: "제15장 불확실성하의 의사결정", difficulty: 4 },
      { id: 716, title: "제16장 종합예산", difficulty: 3 },
      { id: 717, title: "제17장 표준원가계산I (차이분석)", difficulty: 5 },
      { id: 718, title: "제18장 표준원가계산II (종합원가)", difficulty: 5 },
      { id: 719, title: "제19장 판매부문의 성과평가", difficulty: 3 },
      { id: 720, title: "제20장 투자중심점의 성과평가", difficulty: 3 },
      { id: 721, title: "제21장 대체가격결정", difficulty: 5 },
      { id: 722, title: "제22장 재고관리모형/JIT", difficulty: 2 },
      { id: 723, title: "제23장 전략적 원가관리", difficulty: 2 },
      { id: 724, title: "제24장 전략적 성과평가", difficulty: 2 }
    ]
  }
};
