window.kidsEnglishData = [
    { id: 'k1', img: '🚗', en: 'Look at the car!', ko: '저 자동차 봐!', easy_en: 'Car!', easy_ko: '자동차!', mom_en: 'Do you see the car?', mom_ko: '자동차 보여?' },
    { id: 'k2', img: '🦖', en: 'I am a dinosaur!', ko: '나는 공룡이다!', easy_en: 'Dinosaur!', easy_ko: '공룡!', mom_en: 'Roar! Are you a dinosaur?', mom_ko: '크앙! 너 공룡이야?' },
    { id: 'k3', img: '🏃‍♂️', en: 'I can run fast!', ko: '나는 빨리 달릴 수 있어!', easy_en: 'Run fast!', easy_ko: '빨리 달려!', mom_en: 'Wow, you are so fast!', mom_ko: '우와, 진짜 빠르네!' },
    { id: 'k4', img: '💧', en: 'Water, please.', ko: '물 주세요.', easy_en: 'Water!', easy_ko: '물!', mom_en: 'Here is your water.', mom_ko: '여기 물 마셔.' },
    { id: 'k5', img: '🚽', en: 'I need to go potty.', ko: '화장실 가고 싶어요.', easy_en: 'Potty please.', easy_ko: '화장실 갈래요.', mom_en: 'Do you need to go potty?', mom_ko: '화장실 가고 싶어?' },
    { id: 'k6', img: '🍔', en: 'I am hungry!', ko: '배고파요!', easy_en: 'Hungry!', easy_ko: '배고파!', mom_en: 'Let\'s eat something!', mom_ko: '우리 뭐 좀 먹자!' },
    { id: 'k7', img: '⚽', en: 'Let\'s play soccer!', ko: '축구 하자!', easy_en: 'Play ball!', easy_ko: '공놀이 하자!', mom_en: 'Kick the ball to me!', mom_ko: '엄마한테 공 차봐!' },
    { id: 'k8', img: '💤', en: 'I am sleepy.', ko: '졸려요.', easy_en: 'Sleepy.', easy_ko: '졸려.', mom_en: 'Time to sleep now.', mom_ko: '이제 코 자자.' },
    { id: 'k9', img: '🦸‍♂️', en: 'I am super strong!', ko: '나는 엄청 힘이 세!', easy_en: 'Super strong!', easy_ko: '힘 세다!', mom_en: 'Show me your muscles!', mom_ko: '얼마나 힘이 센지 보여줘!' },
    { id: 'k10', img: '✋', en: 'Wait for me!', ko: '나 기다려!', easy_en: 'Wait!', easy_ko: '기다려!', mom_en: 'Okay, I will wait.', mom_ko: '알았어, 엄마가 기다릴게.' },
    { id: 'k11', img: '🧸', en: 'Can I play with this?', ko: '이거 가지고 놀아도 돼요?', easy_en: 'Play?', easy_ko: '놀아도 돼?', mom_en: 'Yes, you can.', mom_ko: '응, 재미있게 놀아.' },
    { id: 'k12', img: '🖐️', en: 'High five!', ko: '하이파이브!', easy_en: 'High five!', easy_ko: '하이파이브!', mom_en: 'Give me a high five!', mom_ko: '엄마랑 하이파이브!' },
    { id: 'k13', img: '🦈', en: 'Baby shark!', ko: '아기 상어!', easy_en: 'Shark!', easy_ko: '상어!', mom_en: 'Let\'s sing baby shark.', mom_ko: '아기상어 노래 부르자.' },
    { id: 'k14', img: '🚂', en: 'Choo choo train!', ko: '칙칙폭폭 기차!', easy_en: 'Train!', easy_ko: '기차!', mom_en: 'Here comes the train!', mom_ko: '기차가 지나간다!' },
    { id: 'k15', img: '😋', en: 'This is yummy.', ko: '이거 맛있어요.', easy_en: 'Yummy!', easy_ko: '맛있어!', mom_en: 'Is it yummy?', mom_ko: '음식 맛있어?' },
    { id: 'k16', img: '🤢', en: 'I don\'t like this.', ko: '이거 싫어요.', easy_en: 'No like.', easy_ko: '싫어.', mom_en: 'You don\'t like it?', mom_ko: '이거 먹기 싫었어?' },
    { id: 'k17', img: '👍', en: 'Good job!', ko: '잘했어!', easy_en: 'Good!', easy_ko: '좋아!', mom_en: 'You did a great job!', mom_ko: '우리 아들 최고네!' },
    { id: 'k18', img: '🛁', en: 'Time to take a bath.', ko: '목욕할 시간이야.', easy_en: 'Bath time.', easy_ko: '목욕하자.', mom_en: 'Let\'s wash your hair.', mom_ko: '머리도 깨끗하게 감자.' },
    { id: 'k19', img: '☀️', en: 'Good morning!', ko: '좋은 아침!', easy_en: 'Morning!', easy_ko: '아침!', mom_en: 'Did you sleep well?', mom_ko: '우리 아기 잘 잤어?' },
    { id: 'k20', img: '🌙', en: 'Good night!', ko: '안녕히 주무세요!', easy_en: 'Night!', easy_ko: '잘자!', mom_en: 'Sweet dreams.', mom_ko: '예쁜 꿈 꿔.' },
    { id: 'k21', img: '👋', en: 'See you later!', ko: '나중에 봐!', easy_en: 'Bye bye!', easy_ko: '안녕!', mom_en: 'Say bye to friends.', mom_ko: '친구들한테 인사하자.' },
    { id: 'k22', img: '🥺', en: 'Can you help me?', ko: '도와주실 수 있어요?', easy_en: 'Help me?', easy_ko: '도와줘?', mom_en: 'Sure, I will help you.', mom_ko: '당연하지 엄마가 도와줄게.' },
    { id: 'k23', img: '🧃', en: 'I want some juice.', ko: '주스 마시고 싶어요.', easy_en: 'Juice please.', easy_ko: '주스 주세요.', mom_en: 'What kind of juice?', mom_ko: '무슨 주스 마실까?' },
    { id: 'k24', img: '🏊‍♂️', en: 'Let\'s go swimming!', ko: '수영하러 가자!', easy_en: 'Swim!', easy_ko: '수영!', mom_en: 'Put on your swimsuit.', mom_ko: '수영복 먼저 입자.' },
    { id: 'k25', img: '🍦', en: 'Ice cream, please.', ko: '아이스크림 주세요.', easy_en: 'Ice cream!', easy_ko: '아이스크림!', mom_en: 'Do you want strawberry?', mom_ko: '딸기맛 먹을까?' },
    { id: 'k26', img: '🐶', en: 'Look at the dog.', ko: '저 강아지 봐.', easy_en: 'Dog!', easy_ko: '강아지!', mom_en: 'The dog is so cute.', mom_ko: '강아지 귀엽다 그지.' },
    { id: 'k27', img: '🩹', en: 'I got a boo-boo.', ko: '나 아야 했어.', easy_en: 'Ouch!', easy_ko: '아야!', mom_en: 'Let mommy kiss it.', mom_ko: '엄마가 호 해줄게.' },
    { id: 'k28', img: '🙌', en: 'I did it!', ko: '내가 해냈어!', easy_en: 'I did it!', easy_ko: '내가 했어!', mom_en: 'I am so proud of you.', mom_ko: '우리 아들 대단한데!' },
    { id: 'k29', img: '❓', en: 'What is this?', ko: '이게 뭐야?', easy_en: 'What?', easy_ko: '뭐야?', mom_en: 'It is a toy.', mom_ko: '이거 장난감이야.' },
    { id: 'k30', img: '🏖️', en: 'I love the beach!', ko: '바다가 너무 좋아!', easy_en: 'Beach!', easy_ko: '바다!', mom_en: 'Let\'s make a sandcastle!', mom_ko: '모래성 만들러 가볼까?' },
    { id: 'k31', img: '🤖', en: 'Look at my robot.', ko: '내 로봇 봐봐.', easy_en: 'My robot!', easy_ko: '내 로봇!', mom_en: 'Your robot is cool.', mom_ko: '너의 로봇 정말 멋지다!' },
    { id: 'k32', img: '🧱', en: 'Let\'s build a tower.', ko: '블록 탑을 쌓자.', easy_en: 'Build blocks!', easy_ko: '블록 탑!', mom_en: 'Stack it up high!', mom_ko: '높이높이 쌓아보자!' },
    { id: 'k33', img: '🎈', en: 'I want the balloon.', ko: '나 풍선 갖고 싶어.', easy_en: 'Balloon!', easy_ko: '풍선!', mom_en: 'Hold it tight.', mom_ko: '날아가지 않게 꽉 잡아.' },
    { id: 'k34', img: '🖍️', en: 'I like drawing.', ko: '나는 그림 그리는 게 좋아.', easy_en: 'Draw!', easy_ko: '그림 그려!', mom_en: 'What are you drawing?', mom_ko: '무엇을 그리고 있어?' },
    { id: 'k35', img: '🎶', en: 'Let\'s sing a song.', ko: '노래 부르자.', easy_en: 'Sing!', easy_ko: '노래해!', mom_en: 'Sing with mommy.', mom_ko: '엄마랑 같이 불러보자.' },
    { id: 'k36', img: '💃', en: 'Look at me dance!', ko: '나 춤추는 것 봐!', easy_en: 'Dance!', easy_ko: '춤 춰!', mom_en: 'You are dancing well.', mom_ko: '점프하면서 잘 추네!' },
    { id: 'k37', img: '🛹', en: 'I want to slide.', ko: '미끄럼틀 탈래.', easy_en: 'Slide!', easy_ko: '미끄럼틀!', mom_en: 'Be careful.', mom_ko: '조심해서 타야 해.' },
    { id: 'k38', img: '🪀', en: 'It is my turn!', ko: '이제 내 차례야!', easy_en: 'My turn!', easy_ko: '내 차례!', mom_en: 'Wait for your turn.', mom_ko: '차례를 예쁘게 기다려야지.' },
    { id: 'k39', img: '🤝', en: 'Let\'s share.', ko: '같이 나눠 쓰자.', easy_en: 'Share!', easy_ko: '나눠 써!', mom_en: 'Good sharing!', mom_ko: '양보하다니 최고야!' },
    { id: 'k40', img: '🏃‍♂️', en: 'Catch me if you can!', ko: '나 잡아봐라!', easy_en: 'Catch me!', easy_ko: '잡아봐!', mom_en: 'Here I come!', mom_ko: '엄마가 잡으러 간다!' },
    { id: 'k41', img: '🦅', en: 'I am a big eagle!', ko: '나는 큰 독수리다!', easy_en: 'Eagle!', easy_ko: '독수리!', mom_en: 'Fly high in the sky!', mom_ko: '하늘 높이 날아봐!' },
    { id: 'k42', img: '⚔️', en: 'I am a knight!', ko: '나는 기사다!', easy_en: 'Knight!', easy_ko: '기사!', mom_en: 'Protect the mommy!', mom_ko: '용감한 기사님 엄마를 지켜줘!' },
    { id: 'k43', img: '🛡️', en: 'Protect the castle!', ko: '성을 지켜라!', easy_en: 'Castle!', easy_ko: '성 지켜!', mom_en: 'You are so brave.', mom_ko: '정말 용감하네.' },
    { id: 'k44', img: '🚀', en: 'Blast off!', ko: '로켓 발사!', easy_en: 'Rocket!', easy_ko: '로켓!', mom_en: 'To the moon!', mom_ko: '달까지 날아가자!' },
    { id: 'k45', img: '👽', en: 'Hello, alien!', ko: '안녕, 외계인!', easy_en: 'Alien!', easy_ko: '외계인!', mom_en: 'Are you from space?', mom_ko: '우주에서 왔어?' },
    { id: 'k46', img: '🚓', en: 'Police car is coming.', ko: '경찰차가 와요.', easy_en: 'Police car!', easy_ko: '경찰차!', mom_en: 'Wee-woo wee-woo.', mom_ko: '삐뽀삐뽀 출동!' },
    { id: 'k47', img: '🚒', en: 'Fire truck is fast.', ko: '소방차가 빨라요.', easy_en: 'Fire truck!', easy_ko: '소방차!', mom_en: 'Put out the fire!', mom_ko: '불을 꺼주세요!' },
    { id: 'k48', img: '🚁', en: 'Helicopter in the sky!', ko: '하늘에 헬리콥터!', easy_en: 'Helicopter!', easy_ko: '헬기!', mom_en: 'Look up there!', mom_ko: '저기 위를 봐봐!' },
    { id: 'k49', img: '🛶', en: 'Let\'s row the boat.', ko: '보트 노를 젓자.', easy_en: 'Boat!', easy_ko: '운전!', mom_en: 'Row, row, row.', mom_ko: '영차 영차 젓자.' },
    { id: 'k50', img: '🏕️', en: 'Let\'s make a tent.', ko: '텐트 만들자.', easy_en: 'Tent!', easy_ko: '텐트!', mom_en: 'It is so cozy.', mom_ko: '텐트 안이 아늑하지.' },
    { id: 'k51', img: '📖', en: 'Read me a story.', ko: '동화책 읽어주세요.', easy_en: 'Story time!', easy_ko: '동화책!', mom_en: 'Which book do you want?', mom_ko: '무슨 책 읽어줄까?' },
    { id: 'k52', img: '🧩', en: 'Where is the piece?', ko: '조각이 어디 있지?', easy_en: 'Puzzle!', easy_ko: '퍼즐!', mom_en: 'Let\'s find it together.', mom_ko: '엄마랑 같이 찾아보자.' },
    { id: 'k53', img: '🥁', en: 'Bang the drum!', ko: '북을 쳐라!', easy_en: 'Drum!', easy_ko: '북 쳐!', mom_en: 'You are so loud!', mom_ko: '소리가 엄청 크네!' },
    { id: 'k54', img: '🎸', en: 'Play the guitar.', ko: '기타를 쳐요.', easy_en: 'Guitar!', easy_ko: '기타!', mom_en: 'Strum the strings.', mom_ko: '징기딩딩 쳐봐.' },
    { id: 'k55', img: '🎹', en: 'Play the piano.', ko: '피아노를 쳐요.', easy_en: 'Piano!', easy_ko: '피아노!', mom_en: 'What a nice melody.', mom_ko: '피아노 소리 예쁘다.' },
    { id: 'k56', img: '🎤', en: 'I am a singer!', ko: '나는 가수다!', easy_en: 'Singer!', easy_ko: '가수!', mom_en: 'Sing beautifully.', mom_ko: '멋지게 불러봐.' },
    { id: 'k57', img: '🤸‍♂️', en: 'Jump high!', ko: '높이 점프해!', easy_en: 'Jump!', easy_ko: '점프!', mom_en: 'Touch the sky!', mom_ko: '하늘까지 닿겠네!' },
    { id: 'k58', img: '🤫', en: 'Hide and seek!', ko: '숨바꼭질!', easy_en: 'Hide!', easy_ko: '숨어!', mom_en: 'Ready or not, here I go!', mom_ko: '다 숨었니, 찾는다!' },
    { id: 'k59', img: '🙈', en: 'Where are you?', ko: '어디 숨었어?', easy_en: 'Where?', easy_ko: '어디야?', mom_en: 'I found you!', mom_ko: '찾았다 우리 아기!' },
    { id: 'k60', img: '👻', en: 'Peek-a-boo!', ko: '까꿍!', easy_en: 'Peekaboo!', easy_ko: '까꿍!', mom_en: 'You surprised me!', mom_ko: '우와 깜짝 놀랐네!' },
    { id: 'k61', img: '✈️', en: 'Look at the airplane!', ko: '비행기 봐!', easy_en: 'Airplane!', easy_ko: '비행기!', mom_en: 'Are you excited?', mom_ko: '비행기 타니까 신나지?' },
    { id: 'k62', img: '☁️', en: 'The clouds are fluffy.', ko: '구름이 푹신푹신해.', easy_en: 'Clouds!', easy_ko: '구름!', mom_en: 'It looks like cotton candy.', mom_ko: '진짜 솜사탕 같네.' },
    { id: 'k63', img: '💺', en: 'Seatbelt on, please.', ko: '안전벨트 매세요.', easy_en: 'Seatbelt!', easy_ko: '벨트!', mom_en: 'Click! It is safe.', mom_ko: '탁! 매면 안전해요.' },
    { id: 'k64', img: '🧳', en: 'This is my bag.', ko: '이건 내 가방이야.', easy_en: 'My bag!', easy_ko: '내 가방!', mom_en: 'What is inside?', mom_ko: '가방에 뭐 들었어?' },
    { id: 'k65', img: '🎫', en: 'Here is my ticket.', ko: '여기 내 표 있어요.', easy_en: 'Ticket!', easy_ko: '표!', mom_en: 'Hold it tightly.', mom_ko: '잃어버리지 않게 잘 쥐어.' },
    { id: 'k66', img: '👨‍✈️', en: 'Hello, pilot!', ko: '안녕 파일럿 아저씨!', easy_en: 'Pilot!', easy_ko: '기장님 안녕!', mom_en: 'Fly us safe!', mom_ko: '조심히 운전해주세요!' },
    { id: 'k67', img: '🛫', en: 'We are going up!', ko: '우리 위로 올라가요!', easy_en: 'Going up!', easy_ko: '올라간다!', mom_en: 'Wow, so high.', mom_ko: '우와 벌써 높이 떴어.' },
    { id: 'k68', img: '🛬', en: 'We are landing!', ko: '우리 착륙해요!', easy_en: 'Landing!', easy_ko: '내려간다!', mom_en: 'Hold my hand.', mom_ko: '엄마 손 꽉 잡아.' },
    { id: 'k69', img: '🎢', en: 'This is fun!', ko: '이거 재밌다!', easy_en: 'Fun!', easy_ko: '재밌어!', mom_en: 'Are you having fun?', mom_ko: '너무 재미있지?' },
    { id: 'k70', img: '😨', en: 'I am a little scared.', ko: '조금 무서워요.', easy_en: 'Scared.', easy_ko: '무서워.', mom_en: 'Mommy is here, it is okay.', mom_ko: '안 무서워 엄마 여깄어.' },
    { id: 'k71', img: '😋', en: 'Airplane food is good.', ko: '비행기 밥 맛있어요.', easy_en: 'Food!', easy_ko: '밥!', mom_en: 'Eat a lot.', mom_ko: '꼭꼭 많이 씹어먹어.' },
    { id: 'k72', img: '🥤', en: 'Apple juice, please.', ko: '사과 주스 주세요.', easy_en: 'Apple juice!', easy_ko: '사과 주스!', mom_en: 'Here you go.', mom_ko: '자, 조심히 마셔.' },
    { id: 'k73', img: '😴', en: 'I need a blanket.', ko: '담요가 필요해요.', easy_en: 'Blanket.', easy_ko: '담요.', mom_en: 'Keep warm.', mom_ko: '따뜻하게 덮자.' },
    { id: 'k74', img: '🗺️', en: 'Where are we going?', ko: '우리 어디 가요?', easy_en: 'Where?', easy_ko: '어디가?', mom_en: 'We are going to Boracay.', mom_ko: '우리 보라카이 가지.' },
    { id: 'k75', img: '🏝️', en: 'We are going to Boracay!', ko: '보라카이에 가요!', easy_en: 'Boracay!', easy_ko: '보라카이!', mom_en: 'It will be fun!', mom_ko: '가면 정말 재밌을 거야!' },
    { id: 'k76', img: '🚢', en: 'I see a ship.', ko: '배가 보여요.', easy_en: 'Ship!', easy_ko: '배 안녕!', mom_en: 'It is a big ship.', mom_ko: '엄청 큰 배가 지나가네.' },
    { id: 'k77', img: '🚌', en: 'Let\'s ride the bus.', ko: '버스 타자.', easy_en: 'Bus!', easy_ko: '버스!', mom_en: 'Sit down please.', mom_ko: '버스에선 앉아야 돼.' },
    { id: 'k78', img: '🚗', en: 'Buckle up in the car.', ko: '차에서 안전벨트 매자.', easy_en: 'Buckle up!', easy_ko: '벨트 매!', mom_en: 'Are you buckled up?', mom_ko: '벨트 꼭 맸어요?' },
    { id: 'k79', img: '🚦', en: 'Red light means stop.', ko: '빨간불은 멈춤이야.', easy_en: 'Stop!', easy_ko: '멈춰!', mom_en: 'Wait for the green light.', mom_ko: '초록불 될때까지 기다려.' },
    { id: 'k80', img: '🟢', en: 'Green light means go.', ko: '초록불은 출발이야.', easy_en: 'Go!', easy_ko: '가자!', mom_en: 'Let\'s go now.', mom_ko: '자 이제 건너가자.' },
    { id: 'k81', img: '🪟', en: 'Look out the window.', ko: '창밖을 봐봐.', easy_en: 'Window!', easy_ko: '창문 밖!', mom_en: 'What do you see?', mom_ko: '밖에 뭐가 보여?' },
    { id: 'k82', img: '☀️', en: 'The sun is bright.', ko: '햇빛이 밝아.', easy_en: 'Sun!', easy_ko: '햇빛!', mom_en: 'Yes, it is sunny.', mom_ko: '응, 햇빛이 뜨거워.' },
    { id: 'k83', img: '🌴', en: 'I see palm trees.', ko: '야자수가 보여.', easy_en: 'Trees!', easy_ko: '나무!', mom_en: 'They are very tall.', mom_ko: '정말 야자수가 키가 크지?' },
    { id: 'k84', img: '🥭', en: 'I want a mango.', ko: '망고 먹고 싶어.', easy_en: 'Mango!', easy_ko: '망고!', mom_en: 'Is it sweet?', mom_ko: '망고 엄청 달달하지?' },
    { id: 'k85', img: '🥥', en: 'Coconut makes me strong!', ko: '코코넛 먹으면 힘이나!', easy_en: 'Coconut!', easy_ko: '코코넛!', mom_en: 'Wow, strong boy.', mom_ko: '코코넛 마시면 튼튼해져요.' },
    { id: 'k86', img: '🍉', en: 'Yummy watermelon!', ko: '맛있는 수박!', easy_en: 'Watermelon!', easy_ko: '수박!', mom_en: 'Eat the red part.', mom_ko: '빨간 부분을 앙 깨물어.' },
    { id: 'k87', img: '🥵', en: 'It is hot today.', ko: '오늘 덥네요.', easy_en: 'Hot.', easy_ko: '더워.', mom_en: 'Drink some water.', mom_ko: '시원한 물 마실까?' },
    { id: 'k88', img: '🥶', en: 'It is cold in here.', ko: '여긴 추워요.', easy_en: 'Cold.', easy_ko: '추워.', mom_en: 'Put on your jacket.', mom_ko: '엄마가 겉옷 입혀줄게.' },
    { id: 'k89', img: '🧢', en: 'I need my hat.', ko: '내 모자가 필요해.', easy_en: 'Hat!', easy_ko: '모자!', mom_en: 'Here is your hat.', mom_ko: '자, 모자 썼다.' },
    { id: 'k90', img: '🕶️', en: 'Cool sunglasses.', ko: '멋진 선글라스.', easy_en: 'Sunglasses!', easy_ko: '선글라스!', mom_en: 'You look so cool.', mom_ko: '우리 아들 정말 멋있네.' },
    { id: 'k91', img: '🏫', en: 'Let\'s go to camp!', ko: '캠프 가자!', easy_en: 'Camp!', easy_ko: '캠프!', mom_en: 'Have fun with friends.', mom_ko: '친구들이랑 엄청 재밌을걸!' },
    { id: 'k92', img: '👩‍🏫', en: 'Hello, teacher!', ko: '선생님 안녕하세요!', easy_en: 'Teacher!', easy_ko: '선생님 안녕!', mom_en: 'Say it loudly.', mom_ko: '씩씩하게 인사해볼까.' },
    { id: 'k93', img: '🧑‍🤝‍🧑', en: 'Hello, friends!', ko: '친구들아 안녕!', easy_en: 'Friends!', easy_ko: '친구들!', mom_en: 'Be nice to friends.', mom_ko: '친구들이랑 사이좋게 놀아.' },
    { id: 'k94', img: '🙋‍♂️', en: 'I am here!', ko: '저 여기 있어요!', easy_en: 'Here!', easy_ko: '여기요!', mom_en: 'Raise your hand high.', mom_ko: '손 번쩍 들고 대답해요.' },
    { id: 'k95', img: '👂', en: 'Listen to the teacher.', ko: '선생님 말씀 듣자.', easy_en: 'Listen!', easy_ko: '들어봐!', mom_en: 'Open your ears.', mom_ko: '귀 쫑긋!' },
    { id: 'k96', img: '🤫', en: 'Be quiet, please.', ko: '조용히 해주세요.', easy_en: 'Quiet!', easy_ko: '조용히!', mom_en: 'Shh, inside voice.', mom_ko: '쉿, 조용조용 말해요.' },
    { id: 'k97', img: '🪑', en: 'Sit down, please.', ko: '자리에 앉으세요.', easy_en: 'Sit down!', easy_ko: '앉아!', mom_en: 'Criss-cross applesauce.', mom_ko: '자리에 털썩.' },
    { id: 'k98', img: '🚶‍♂️', en: 'Stand up, please.', ko: '일어나세요.', easy_en: 'Stand up!', easy_ko: '일어나!', mom_en: 'Stand up straight.', mom_ko: '똑바로 서볼까?' },
    { id: 'k99', img: '✋', en: 'Raise your hand.', ko: '손을 드세요.', easy_en: 'Hand up!', easy_ko: '손 들어!', mom_en: 'Who wants to try?', mom_ko: '해볼 사람 번쩍!' },
    { id: 'k100', img: '✏️', en: 'I have a pencil.', ko: '나는 연필이 있어요.', easy_en: 'Pencil!', easy_ko: '연필!', mom_en: 'Write your name.', mom_ko: '거기에 네 이름 써봐.' },
    { id: 'k101', img: '✂️', en: 'Cut with scissors.', ko: '가위로 잘라요.', easy_en: 'Scissors!', easy_ko: '가위!', mom_en: 'Be careful with scissors.', mom_ko: '가위 쓸 땐 항상 조심조심!' },
    { id: 'k102', img: '🖍️', en: 'Pass the crayon.', ko: '크레용 좀 주세요.', easy_en: 'Crayon!', easy_ko: '크레용!', mom_en: 'What color do you want?', mom_ko: '어떤 색깔 필요해?' },
    { id: 'k103', img: '📝', en: 'I am writing.', ko: '나는 글씨를 써요.', easy_en: 'Writing!', easy_ko: '글씨 써!', mom_en: 'What are you writing?', mom_ko: '무엇을 쓰고 있니?' },
    { id: 'k104', img: '🎨', en: 'Look at my picture.', ko: '내 그림 보세요.', easy_en: 'My picture!', easy_ko: '내 그림!', mom_en: 'It is a beautiful picture.', mom_ko: '그림 정말 잘 그렸네.' },
    { id: 'k105', img: '👏👏', en: 'Clap your hands!', ko: '박수 치세요!', easy_en: 'Clap!', easy_ko: '박수!', mom_en: 'To the rhythm!', mom_ko: '음악 맞춰서 짝짝짝!' },
    { id: 'k106', img: '⭕', en: 'Make a circle.', ko: '둥글게 모이세요.', easy_en: 'Circle!', easy_ko: '둥글게 둥글게!', mom_en: 'Hold hands.', mom_ko: '손잡고 동그라미 만들자.' },
    { id: 'k107', img: '🧹', en: 'Clean up time.', ko: '정리할 시간이야.', easy_en: 'Clean up!', easy_ko: '일어나 치워!', mom_en: 'Put the toys away.', mom_ko: '우리 장난감 얼른 정리하자.' },
    { id: 'k108', img: '🧺', en: 'Put it in the box.', ko: '상자 안에 넣어.', easy_en: 'In the box!', easy_ko: '모아!', mom_en: 'Good job cleaning.', mom_ko: '스스로 정리도 잘하네.' },
    { id: 'k109', img: '🚻', en: 'Wash your hands.', ko: '손을 씻어요.', easy_en: 'Wash hands!', easy_ko: '손 씻어!', mom_en: 'Use soap.', mom_ko: '비누칠 싹싹.' },
    { id: 'k110', img: '🦠', en: 'Bye bye germs.', ko: '세균 안녕.', easy_en: 'Germs bye!', easy_ko: '세균 바바이!', mom_en: 'Now your hands are clean.', mom_ko: '이제 손 깨끗하네.' },
    { id: 'k111', img: '🍎', en: 'Snack time!', ko: '간식 시간!', easy_en: 'Snack!', easy_ko: '간식!', mom_en: 'Are you hungry?', mom_ko: '벌써 출출해?' },
    { id: 'k112', img: '🥛', en: 'Milk, please.', ko: '우유 주세요.', easy_en: 'Milk.', easy_ko: '우유.', mom_en: 'Drink it all.', mom_ko: '우유 꿀꺽 다 마셔버려.' },
    { id: 'k113', img: '🙋', en: 'Can I try?', ko: '내가 해봐도 돼요?', easy_en: 'My turn?', easy_ko: '나도 할래!', mom_en: 'Yes, it is your turn.', mom_ko: '응, 이제 네가 해봐.' },
    { id: 'k114', img: '🙅‍♂️', en: 'No, thank you.', ko: '아니요 괜찮아요.', easy_en: 'No thanks.', easy_ko: '괜찮아.', mom_en: 'Are you full?', mom_ko: '벌써 배불러?' },
    { id: 'k115', img: '🙏', en: 'Help me, please.', ko: '도와주세요.', easy_en: 'Help!', easy_ko: '도와줘!', mom_en: 'What do you need?', mom_ko: '무슨 도움이 필요해?' },
    { id: 'k116', img: '😭', en: 'I am sad.', ko: '나 슬퍼요.', easy_en: 'Sad.', easy_ko: '슬퍼.', mom_en: 'Don\'t be sad.', mom_ko: '슬퍼하지마 뚝!' },
    { id: 'k117', img: '😃', en: 'I am happy!', ko: '나 행복해요!', easy_en: 'Happy!', easy_ko: '행복해!', mom_en: 'Mommy is happy too.', mom_ko: '엄마도 네가 행복해서 좋아.' },
    { id: 'k118', img: '😠', en: 'I am angry.', ko: '나 화났어.', easy_en: 'Angry.', easy_ko: '화났어.', mom_en: 'Take a deep breath.', mom_ko: '후~ 심호흡 한번 해봐.' },
    { id: 'k119', img: '🥺', en: 'I miss mommy.', ko: '엄마 보고 싶어요.', easy_en: 'Mommy.', easy_ko: '엄마 보고파.', mom_en: 'Mommy will be back soon.', mom_ko: '엄마 금방 데리러 갈게.' },
    { id: 'k120', img: '😎', en: 'I am brave!', ko: '나는 용감해!', easy_en: 'Brave!', easy_ko: '난 용감해!', mom_en: 'Yes, you are so brave.', mom_ko: '맞아 멋지고 용감한 형아지!' },
    { id: 'k121', img: '🌊', en: 'Look at the sea!', ko: '바다 좀 봐!', easy_en: 'Sea!', easy_ko: '바다!', mom_en: 'The sea is so blue.', mom_ko: '바다 색깔 정말 파랗다.' },
    { id: 'k122', img: '🏖️', en: 'Let\'s make a sandcastle.', ko: '모래성 만들자.', easy_en: 'Sandcastle!', easy_ko: '모래성!', mom_en: 'We need more sand.', mom_ko: '모래가 좀 더 있어야겠네.' },
    { id: 'k123', img: '🐚', en: 'I found a shell.', ko: '조개껍데기 찾았어.', easy_en: 'Shell!', easy_ko: '조개!', mom_en: 'Can you hear the ocean?', mom_ko: '귀에 대봐 바다 소리 나?' },
    { id: 'k124', img: '🦀', en: 'Look, a tiny crab.', ko: '봐, 작은 게야.', easy_en: 'Crab!', easy_ko: '꽃게!', mom_en: 'It walks sideways.', mom_ko: '옆으로 슝 걷는 꽃게네.' },
    { id: 'k125', img: '🐟', en: 'Fish are swimming.', ko: '물고기가 헤엄쳐.', easy_en: 'Fish!', easy_ko: '물고기!', mom_en: 'Many colorful fish.', mom_ko: '진짜 물고기 엄청 많다.' },
    { id: 'k126', img: '🐢', en: 'A slow turtle.', ko: '느린 거북이.', easy_en: 'Turtle!', easy_ko: '거북이!', mom_en: 'Turtle is swimming.', mom_ko: '거북이도 수영하려나봐.' },
    { id: 'k127', img: '🩱', en: 'Put on my swimsuit.', ko: '수영복 입자.', easy_en: 'Swimsuit!', easy_ko: '수영복!', mom_en: 'You look great.', mom_ko: '수영복 입으니 멋진데.' },
    { id: 'k128', img: '🥽', en: 'Where are my goggles?', ko: '물안경 어딨지?', easy_en: 'Goggles!', easy_ko: '물안경!', mom_en: 'They are on your head.', mom_ko: '머리 위에 써있네.' },
    { id: 'k129', img: '🍩', en: 'I need my tube.', ko: '내 튜브가 필요해.', easy_en: 'Tube!', easy_ko: '튜브!', mom_en: 'Hold onto the tube.', mom_ko: '튜브 꽉 잡아.' },
    { id: 'k130', img: '🛟', en: 'Life jacket on!', ko: '구명조끼 입기!', easy_en: 'Jacket!', easy_ko: '구명조끼!', mom_en: 'Safety first.', mom_ko: '안전이 제일 중요하지.' },
    { id: 'k131', img: '💦', en: 'Splash the water.', ko: '물장구 치자.', easy_en: 'Splash!', easy_ko: '물장구!', mom_en: 'Don\'t splash in eyes.', mom_ko: '눈에는 안 들어가게 부드럽게.' },
    { id: 'k132', img: '😲', en: 'The water is cold!', ko: '물이 차가워요!', easy_en: 'Cold!', easy_ko: '차가워!', mom_en: 'Move your body to get warm.', mom_ko: '움직이면 곧 따뜻해질거야.' },
    { id: 'k133', img: '😆', en: 'The water is warm.', ko: '물이 따뜻해요.', easy_en: 'Warm.', easy_ko: '따뜻해.', mom_en: 'It feels good.', mom_ko: '아 따뜻해서 좋다 그지?' },
    { id: 'k134', img: '🏄‍♂️', en: 'I am surfing!', ko: '나 파도 타요!', easy_en: 'Surfing!', easy_ko: '파도 타기!', mom_en: 'Wow, good balance.', mom_ko: '우와 안 넘어지네.' },
    { id: 'k135', img: '🚤', en: 'A fast boat!', ko: '빠른 보트!', easy_en: 'Boat!', easy_ko: '보트타기!', mom_en: 'It goes zoom!', mom_ko: '엄청 빨리 지나간다.' },
    { id: 'k136', img: '🍦', en: 'I want ice cream.', ko: '아이스크림 먹을래.', easy_en: 'Ice cream!', easy_ko: '아이스크림!', mom_en: 'Eat it before it melts.', mom_ko: '녹기 전에 얼른 먹어.' },
    { id: 'k137', img: '🥤', en: 'I am thirsty.', ko: '목말라요.', easy_en: 'Thirsty.', easy_ko: '목말라.', mom_en: 'Drink slowly.', mom_ko: '천천히 마셔.' },
    { id: 'k138', img: '🧊', en: 'More ice, please.', ko: '얼음 더 주세요.', easy_en: 'Ice!', easy_ko: '얼음!', mom_en: 'It is so cold.', mom_ko: '아후 차가워라.' },
    { id: 'k139', img: '🧴', en: 'Put on sunscreen.', ko: '선크림 바르자.', easy_en: 'Sunscreen!', easy_ko: '선크림!', mom_en: 'We don\'t want sunburns.', mom_ko: '얼굴 안 타게 꼼꼼히 바르자.' },
    { id: 'k140', img: '⛱️', en: 'Let\'s rest in the shade.', ko: '그늘에서 쉬자.', easy_en: 'Rest.', easy_ko: '쉬자.', mom_en: 'Sit here and relax.', mom_ko: '여기에 앉아서 푹 쉬어.' },
    { id: 'k141', img: '😴', en: 'I need a nap.', ko: '낮잠 자야 됨.', easy_en: 'Nap.', easy_ko: '낮잠 잘래.', mom_en: 'Sleep well.', mom_ko: '푹 자고 일어나.' },
    { id: 'k142', img: '🚿', en: 'Wash with water.', ko: '물로 씻자.', easy_en: 'Wash!', easy_ko: '씻자!', mom_en: 'Wash away the sand.', mom_ko: '모래 깨끗하게 씻어내야지.' },
    { id: 'k143', img: '🛁', en: 'Where is the towel?', ko: '수건 어딨어?', easy_en: 'Towel!', easy_ko: '수건!', mom_en: 'Here it is.', mom_ko: '여기 수건 가져왔지.' },
    { id: 'k144', img: '👕', en: 'Put on my clothes.', ko: '내 옷 입자.', easy_en: 'Clothes!', easy_ko: '옷!', mom_en: 'Put your arms in.', mom_ko: '자 여기 팔 집어넣고.' },
    { id: 'k145', img: '👟', en: 'Where are my shoes?', ko: '내 신발 어딨어?', easy_en: 'Shoes!', easy_ko: '신발!', mom_en: 'Put on your shoes.', mom_ko: '이제 신발 신을 준비할까.' },
    { id: 'k146', img: '🥰', en: 'I love you!', ko: '사랑해요!', easy_en: 'Love you!', easy_ko: '사랑해!', mom_en: 'Mommy loves you too.', mom_ko: '엄마도 완전 사랑해.' },
    { id: 'k147', img: '🤗', en: 'Give me a hug.', ko: '안아주세요.', easy_en: 'Hug!', easy_ko: '안아줘!', mom_en: 'A big warm hug!', mom_ko: '꽉 안아줘야지!' },
    { id: 'k148', img: '💋', en: 'Give me a kiss.', ko: '뽀뽀해주세요.', easy_en: 'Kiss!', easy_ko: '쪽!', mom_en: 'Mwah!', mom_ko: '쪽!' },
    { id: 'k149', img: '🙏', en: 'Thank you so much.', ko: '너무 감사합니다.', easy_en: 'Thank you.', easy_ko: '고마워!', mom_en: 'You are so polite.', mom_ko: '예의도 정말 바르네.' },
    { id: 'k150', img: '😇', en: 'You are welcome.', ko: '천만에요.', easy_en: 'Welcome.', easy_ko: '천만에.', mom_en: 'Thank you.', mom_ko: '엄마도 고마워.' },
    { id: 'k151', img: '🥺', en: 'I am sorry.', ko: '미안합니다.', easy_en: 'Sorry.', easy_ko: '미안해.', mom_en: 'It is okay, don\'t do it again.', mom_ko: '괜찮아 다음엔 조심해.' },
    { id: 'k152', img: '😊', en: 'It is okay.', ko: '괜찮아요.', easy_en: 'Okay.', easy_ko: '괜찮아.', mom_en: 'You are so kind.', mom_ko: '착하기도 하지.' },
    { id: 'k153', img: '🙏', en: 'Please.', ko: '부탁합니다/주세요.', easy_en: 'Please.', easy_ko: '제발~', mom_en: 'Say please correctly.', mom_ko: '예쁘게 부탁해볼까.' },
    { id: 'k154', img: '🤩', en: 'You are the best!', ko: '최고예요!', easy_en: 'The best!', easy_ko: '최고!', mom_en: 'You are my best boy.', mom_ko: '네가 엄마한텐 최고지!' },
    { id: 'k155', img: '😁', en: 'I am so happy.', ko: '나는 너무 행복해요.', easy_en: 'Happy.', easy_ko: '행복해.', mom_en: 'Always be happy.', mom_ko: '늘 행복하게 지내자.' },
    { id: 'k156', img: '🥳', en: 'Today was fun.', ko: '오늘 재밌었어요.', easy_en: 'Fun!', easy_ko: '재밌어!', mom_en: 'Tomorrow will be fun too.', mom_ko: '내일도 엄청 재밌을 거야.' },
    { id: 'k157', img: '📸', en: 'Take a picture!', ko: '사진 찍어줘!', easy_en: 'Picture!', easy_ko: '사진!', mom_en: 'Say cheese!', mom_ko: '하나 둘 셋 치~즈!' },
    { id: 'k158', img: '✌️', en: 'Cheese!', ko: '치즈!', easy_en: 'Cheese!', easy_ko: '치즈!', mom_en: 'Smile nicely.', mom_ko: '김치 예쁘게 웃어봐.' },
    { id: 'k159', img: '✈️', en: 'I love Boracay!', ko: '보라카이 너무 좋아!', easy_en: 'Boracay!', easy_ko: '보라카이!', mom_en: 'Let\'s come back again.', mom_ko: '다음에 또 놀러오자.' }
];
